version: '3.4'
 
services:
    postgres:
        container_name: postgres
        image: postgres:13.9
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: changeme
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - /data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - atlassian
        
    crowd:
        container_name: atlassian-crowd
        image: atlassian/crowd:latest
        volumes:
            - /data/atlassian/crowd-home:/var/atlassian/application-data/crowd
        ports:
            - "8095:8095"
        depends_on:
            - postgres
        networks:
            - atlassian
 
    jira:
        container_name: atlassian-jira-software
        image: atlassian/jira-software:latest
        environment:
            # Database
            - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/jira
            - ATL_JDBC_USER=jira
            - ATL_JDBC_PASSWORD=changeme
            - ATL_DB_DRIVER=org.postgresql.Driver
            - ATL_DB_TYPE=postgres72
        volumes:
            - /data/atlassian/jira-home:/var/atlassian/application-data/jira
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        networks:
            - atlassian
 
    confluence:
        container_name: atlassian-confluence-server
        image: atlassian/confluence-server:latest
        environment:
            # Database
            - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/confluence
            - ATL_JDBC_USER=confluence
            - ATL_JDBC_PASSWORD=changeme
            - ATL_DB_TYPE=postgresql
        volumes:
            - /data/atlassian/confluence-home:/var/atlassian/application-data/confluence
        ports:
            - "8090:8090"
        depends_on:
            - postgres
        networks:
            - atlassian
 
    bitbucket:
        container_name: atlassian-bitbucket-server
        image: atlassian/bitbucket-server:latest
        environment:
            # Database
            - JDBC_URL=jdbc:postgresql://postgres:5432/bitbucket
            - JDBC_USER=bitbucket
            - JDBC_PASSWORD=changeme
            - JDBC_DRIVER=org.postgresql.Driver
        volumes:
            - /data/atlassian/bitbucket-home:/var/atlassian/application-data/bitbucket
        ports:
            - "7990:7990"
        depends_on:
            - postgres
        networks:
            - atlassian
 
    bamboo:
        container_name: atlassian-bamboo-server
        image: atlassian/bamboo-server:latest
        environment:
            # Database
            - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/bamboo
            - ATL_JDBC_USER=bamboo
            - ATL_JDBC_PASSWORD=changeme
            - ATL_DB_TYPE=postgresql
        volumes:
            - /data/atlassian/bamboo-home:/var/atlassian/application-data/bamboo
        ports:
            - "8085:8085"
        depends_on:
            - postgres
        networks:
            - atlassian
 
networks:
    atlassian:
        name: atlassian
        driver: bridge