version: '3.4'
 
services:
    jira-postgres:
        container_name: jira-postgres
        image: postgres:${PG_IMAGE_VERSION:-13}
        environment:
            POSTGRES_USER: ${PG_USER:-postgres}
            POSTGRES_PASSWORD: ${PG_PASSWORD:-changeme}
        volumes:
            - ./docker-entrypoint-initdb.d/jira.sh:/docker-entrypoint-initdb.d/jira.sh
            - jira-pg:/var/lib/postgresql/data
        ports:
            - "5432"
        networks:
            - atlassian
            
            
    crowd-postgres:
        container_name: crowd-postgres
        image: postgres:${PG_IMAGE_VERSION:-13}
        environment:
            POSTGRES_USER: ${PG_USER:-postgres}
            POSTGRES_PASSWORD: ${PG_PASSWORD:-changeme}
        volumes:
            - ./docker-entrypoint-initdb.d/crowd.sh:/docker-entrypoint-initdb.d/crowd.sh
            - crowd-pg:/var/lib/postgresql/data
        ports:
            - "5432"
        networks:
            - atlassian
            
            
    confluence-postgres:
        container_name: confluence-postgres
        image: postgres:${PG_IMAGE_VERSION:-13}
        environment:
            POSTGRES_USER: ${PG_USER:-postgres}
            POSTGRES_PASSWORD: ${PG_PASSWORD:-changeme}
        volumes:
            - ./docker-entrypoint-initdb.d/confluence.sh:/docker-entrypoint-initdb.d/confluence.sh
            - confluence-pg:/var/lib/postgresql/data
        ports:
            - "5432"
        networks:
            - atlassian
            
            
    jsm-postgres:
        container_name: jsm-postgres
        image: postgres:${PG_IMAGE_VERSION:-13}
        environment:
            POSTGRES_USER: ${PG_USER:-postgres}
            POSTGRES_PASSWORD: ${PG_PASSWORD:-changeme}
        volumes:
            - ./docker-entrypoint-initdb.d/jsm.sh:/docker-entrypoint-initdb.d/jsm.sh
            - jsm-pg:/var/lib/postgresql/data
        ports:
            - "5432"
        networks:
            - atlassian
            
            
    bitbucket-postgres:
        container_name: bitbucket-postgres
        image: postgres:${PG_IMAGE_VERSION:-13}
        environment:
            POSTGRES_USER: ${PG_USER:-postgres}
            POSTGRES_PASSWORD: ${PG_PASSWORD:-changeme}
        volumes:
            - ./docker-entrypoint-initdb.d/bitbucket.sh:/docker-entrypoint-initdb.d/bitbucket.sh
            - bitbucket-pg:/var/lib/postgresql/data
        ports:
            - "5432"
        networks:
            - atlassian
            
            
    bamboo-postgres:
        container_name: bamboo-postgres
        image: postgres:${PG_IMAGE_VERSION:-13}
        environment:
            POSTGRES_USER: ${PG_USER:-postgres}
            POSTGRES_PASSWORD: ${PG_PASSWORD:-changeme}
        volumes:
            - ./docker-entrypoint-initdb.d/bamboo.sh:/docker-entrypoint-initdb.d/bamboo.sh
            - bamboo-pg:/var/lib/postgresql/data
        ports:
            - "5432"
        networks:
            - atlassian
            
        
    crowd:
        container_name: crowd${CONTAINER_NAME:-}
        image: atlassian/crowd:${CROWD_VERSION:-latest}
        environment:
            # Database
            - ATL_JDBC_URL=jdbc:postgresql://${CROWD_PG_URL:-crowd-postgres}:5432/${CROWD_PG_DB:-crowd}
            - ATL_JDBC_USER=${CROWD_PG_USER:-crowd}
            - ATL_JDBC_PASSWORD=${CROWD_PG_PASSWORD:-changeme}
            - ATL_PROXY_NAME=crowd${DOMAIN_NAME:-}
            - ATL_PROXY_PORT=${PROXY_PORT:-80}
            - ATL_TOMCAT_SCHEME=${PROXY_SCHEME:-http}
            - ATL_TOMCAT_SECURE=${PROXY_SSL:-false}
            - ATL_TOMCAT_PORT=${CROWD_PORT:-8095}
            - TZ=Asia/Seoul
        volumes:
            - ${CROWD_VOLUME:-crowd-data}:/var/atlassian/application-data/crowd
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "${CROWD_PORT:-8095}:${CROWD_PORT:-8095}"
        networks:
            - atlassian
            
 
    jira:
        container_name: jira${CONTAINER_NAME:-}
        image: atlassian/jira-software:${JIRA_VERSION:-latest}
        environment:
            # Database
            - ATL_JDBC_URL=jdbc:postgresql://${JIRA_PG_URL:-jira-postgres}:5432/${JIRA_PG_DB:-jira}
            - ATL_JDBC_USER=${JIRA_PG_USER:-jira}
            - ATL_JDBC_PASSWORD=${JIRA_PG_PASSWORD:-changeme}
            - ATL_PG_DRIVER=org.postgresql.Driver
            - ATL_DB_TYPE=postgres72
            - ATL_PROXY_NAME=jira${DOMAIN_NAME:-}
            - ATL_PROXY_PORT=${PROXY_PORT:-80}
            - ATL_TOMCAT_SCHEME=${PROXY_SCHEME:-http}
            - ATL_TOMCAT_SECURE=${PROXY_SSL:-false}
            - ATL_TOMCAT_PORT=${JIRA_PORT:-8080}
            - TZ=Asia/Seoul
            - JVM_MAXIMUM_MEMORY=8192m
        volumes:
            - ${JIRA_VOLUME:-jira-data}:/var/atlassian/application-data/jira
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "${JIRA_PORT:-8080}:${JIRA_PORT:-8080}"
        networks:
            - atlassian
            
            
    jsm:
        container_name: jsm${CONTAINER_NAME:-}
        image: atlassian/jira-servicemanagement:${JSM_VERSION:-latest}
        environment:
            # Database
            - ATL_JDBC_URL=jdbc:postgresql://${JSM_PG_URL:-jsm-postgres}:5432/${JSM_PG_DB:-jsm}
            - ATL_JDBC_USER=${JSM_PG_USER:-jsm}
            - ATL_JDBC_PASSWORD=${JSM_PG_PASSWORD:-changeme}
            - ATL_PG_DRIVER=org.postgresql.Driver
            - ATL_DB_TYPE=postgres72
            - ATL_PROXY_NAME=jsm${DOMAIN_NAME:-}
            - ATL_PROXY_PORT=${PROXY_PORT:-80}
            - ATL_TOMCAT_SCHEME=${PROXY_SCHEME:-http}
            - ATL_TOMCAT_SECURE=${PROXY_SSL:-false}
            - ATL_TOMCAT_PORT=${JSM_PORT:-8081}
            - TZ=Asia/Seoul
        volumes:
            - ${JSM_VOLUME:-jsm-data}:/var/atlassian/application-data/jira
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "${JSM_PORT:-8081}:${JSM_PORT:-8081}"
        networks:
            - atlassian
            
 
    confluence:
        container_name: confluence${CONTAINER_NAME:-}
        image: atlassian/confluence:${CONFLUENCE_VERSION:-latest}
        environment:
            # Database
            - ATL_JDBC_URL=jdbc:postgresql://${CONFLUENCE_PG_URL:-confluence-postgres}:5432/${CONFLUENCE_PG_DB:-confluence}
            - ATL_JDBC_USER=${CONFLUENCE_PG_USER:-confluence}
            - ATL_JDBC_PASSWORD=${CONFLUENCE_PG_PASSWORD:-changeme}
            - ATL_DB_TYPE=postgresql
            - ATL_PROXY_NAME=confluence${DOMAIN_NAME:-}
            - ATL_PROXY_PORT=${PROXY_PORT:-80}
            - ATL_TOMCAT_SCHEME=${PROXY_SCHEME:-http}
            - ATL_TOMCAT_SECURE=${PROXY_SSL:-false}
            - ATL_TOMCAT_PORT=${CONFLUENCE_PORT:-8090}
            - TZ=Asia/Seoul
        volumes:
            - ${CONFLUENCE_VOLUME:-confluence-data}:/var/atlassian/application-data/confluence
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "${CONFLUENCE_PORT:-8090}:${CONFLUENCE_PORT:-8090}"
            - "${CONFLUENCE_SYNC_PORT:-8091}:8091"
        networks:
            - atlassian
            
 
    bitbucket:
        container_name: bitbucket${CONTAINER_NAME:-}
        image: atlassian/bitbucket:${BITBUCKET_VERSION:-latest}
        environment:
            # Database
            - JDBC_URL=jdbc:postgresql://${BITBUCKET_PG_URL:-bitbucket-postgres}:5432/${BITBUCKET_PG_DB:-bitbucket}
            - JDBC_USER=${BITBUCKET_PG_USER:-bitbucket}
            - JDBC_PASSWORD=${BITBUCKET_PG_PASSWORD:-changeme}
            - JDBC_DRIVER=org.postgresql.Driver
            - SERVER_PROXY_NAME=bitbucket${DOMAIN_NAME:-}
            - SERVER_PROXY_PORT=${PROXY_PORT:-80}
            - SERVER_SCHEME=${PROXY_SCHEME:-http}
            - SERVER_SECURE=${PROXY_SSL:-false}
            - TZ=Asia/Seoul
        volumes:
            - ${BITBUCKET_VOLUME:-bitbucket-data}:/var/atlassian/application-data/bitbucket
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "${BITBUCKET_PORT:-7990}:7990"
        networks:
            - atlassian

    bitbucket-mesh:
        container_name: bitbucket-mesh${CONTAINER_NAME:-}
        image: atlassian/bitbucket-mesh:${BITBUCKET_MESH_VERSION:-latest}
        environment:
            - TZ=Asia/Seoul
        ports:
            - "7777:7777"
        volumes:
            - bitbucket-mesh-data:/var/atlassian/application-data/mesh
            - /etc/localtime:/etc/localtime:ro
        networks:
            - atlassian




    bamboo:
        container_name: bamboo${CONTAINER_NAME:-}
        image: atlassian/bamboo:${BAMBOO_VERSION:-latest}
        environment:
            # Database
            - ATL_JDBC_URL=jdbc:postgresql://${BAMBOO_PG_URL:-bamboo-postgres}:5432/${BAMBOO_PG_DB:-bamboo}
            - ATL_JDBC_USER=${BAMBOO_PG_USER:-bamboo}
            - ATL_JDBC_PASSWORD=${BAMBOO_PG_PASSWORD:-changeme}
            - ATL_DB_TYPE=postgresql
            - ATL_PROXY_NAME=bamboo${DOMAIN_NAME:-}
            - ATL_PROXY_PORT=${PROXY_PORT:-80}
            - ATL_TOMCAT_SCHEME=${PROXY_SCHEME:-http}
            - ATL_TOMCAT_SECURE=${PROXY_SSL:-false}
            - ATL_TOMCAT_PORT=${BAMBOO_PORT:-8085}
            - TZ=Asia/Seoul
        volumes:
            - ${BAMBOO_VOLUME:-bamboo-data}:/var/atlassian/application-data/bamboo
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "${BAMBOO_PORT:-8085}:${BAMBOO_PORT:-8085}"
        networks:
            - atlassian

    watchtower:
        container_name: watchtower
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - atlassian

networks:
    atlassian:
        name: atlassian
        driver: bridge
        
volumes:
    crowd-pg:
    jira-pg:
    jsm-pg:
    confluence-pg:
    bitbucket-pg:
    bamboo-pg:
    crowd-data:
    jira-data:
    jsm-data:
    confluence-data:
    bitbucket-data:
    bamboo-data:
    bitbucket-mesh-data:
